version: 0.2

env:
  variables:
    SAM_CLI_TELEMETRY: 0
    TZ: Australia/Sydney
    APP_CONFIG_GROUP_PREFIX: bla

phases:
  install:
    runtime-versions:
      java: corretto21.x
      # python: 3.x
      nodejs: 20.x
    commands:
      - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime
      - echo $TZ > /etc/timezone
      - date
      - npm install -g aws-cdk

  build:
    commands:
      - date
      - ps -ef
      - echo $HOME
      - mkdir -p $HOME/.gradle
      - echo 'org.gradle.console=plain' > $HOME/.gradle/gradle.properties
      - echo 'GRADLE_WRAPPER_DISTS_HOME=GRADLE_USER_HOME' >> $HOME/.gradle/gradle.properties
      - export APP_CONFIG_ROOT_CONFIG_FOLDER=$CODEBUILD_SRC
      - cd $CODEBUILD_SRC_DIR_Artifact_Checkout_Source_GitHub_CI_CD_Source
      - pwd
      - ls -lAR
      - env | grep JAVA
      - env | grep JDK
      - env | grep JRE
      - java -version
      - ./gradlew --version
      - du -hs /root/.gradle
      - du -hs /root/.gradle/caches
      - du -hs /root/.gradle/wrapper
      - du -hs /root/.m2
      - cdk --no-color --ci diff
      # - pwd
      # - env | grep CODEBUILD_SRC
      # - ls -lR
      # - ls -lR $CODEBUILD_SRC_DIR_Artifact_Checkout_Source_GitHub_CI_CD_Source
      # - java -version
      # - cdk --version
      # - git clone --depth 1 --branch feature/perf-test  https://github.com/leonjohan3/application-configuration-store-cicd.git
      # - cd application-configuration-store-cicd/
      # - python -m venv .venv --clear --prompt venv --upgrade-deps
      # - source .venv/bin/activate
      # - pwd
      # - ls -l
      # - pip install -r requirements.txt
      # - mkdir -p cicd_app_tests/invalid_config_folder_structures/with_folder_in_place_of_a_configuration_file/my_application/my_environment/misplaced_folder/
      # - mkdir -p cicd_app_tests/invalid_config_folder_structures/without_a_configuration_file/my_application/my_environment/
      # - mkdir -p cicd_app_tests/invalid_config_folder_structures/without_any_environment_folders/my_application/
      # - mkdir -p cicd_app_tests/provided_input/.git
      # - touch cicd_app_tests/provided_input/.git/dummy_file.txt
      # - mkdir build
      # - python -m pytest cicd_app_tests

cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'
    - '/root/.m2/**/*'
#    - '/root/.cache/pip/**/*'
